### ISSUE TITLE
Feature: bundle dashboard with helm-chart

### ISSUE THREAD

**Issue by jcpunk** [enix/x509-certificate-exporter#136]
Kube-prometheus-stack has a pattern for including grafana dashboards with the chart.

https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/grafana/configmap-dashboards.yaml

Can the recommended dashboard be added to this chart in a similar method?

**Comment by npdgm** [comment]
Hi @jcpunk
Thanks a lot for the suggestion, that was a great idea!
Cheers
