### ISSUE TITLE
Listening address

### ISSUE THREAD

**Issue by tacerus** [enix/x509-certificate-exporter#17]
Hi,

apologies if I missed something - but from what I can see it's only possible to specify the listening port via the available command line arguments. Is there a way to specify the listening/bind address as well?

Best,
Georg

**Comment by npdgm** [comment]
Hi Georg,
You are correct, it's missing an argument to specify the listening address.
We'll implement that shortly.
Cheers

**Comment by tacerus** [comment]
Oh amazing - Thank you so much! :)

**Comment by npdgm** [comment]
@tacerus version 2.11.0 was released yesterday with the option for specifying a listening address.

I wish we didn't break existing arguments to the program and simply add a new one, however this obvious answer to the need was inelegant in some ways and less powerful with regard to IPv6. This implementation is what Golang applications tend to use, and matches many popular exporters.
Most users of this project seem to use the Helm Chart on Kubernetes and fortunately this change is made transparent to them.

So argument `--port` was deprecated and you should use `--listen-address` instead. It can take a port number or an address/port pair.
The default is `--listen-address=:9793` and will listen on our default port for any IPv4/IPv6 address, just like it used to be.
A few examples :
- `--listen-address=:9793`
- `--listen-address=127.0.0.1:9793`
- `--listen-address=[::1]:9793`
- `--listen-address=10.1.2.3:9793`
- `--listen-address=[2001:abc::123]:9793`

I hope this will suit you.

Cheers
