### ISSUE TITLE
Prometheus metrics was collected before with the same name and label values error

### ISSUE THREAD

**Issue by testisnullus** [enix/x509-certificate-exporter#18]
Hello! I have installed x509-certificate-exporter for prometheus metrics expose on my k8s cluster.  When I go to the endpoint with prometheus metrics (http://localhost:9793/metrics) I get some errors like:
```
6 error(s) occurred:
* collected metric "x509_cert_expired" { label:<name:"issuer_C" value:"US" > label:<name:"issuer_CN" value:"xxx" > label:<name:"issuer_O" value:"IRCS" > label:<name:"secret_key" value:"cert.crt" > label:<name:"secret_name" value:"default-cert" > label:<name:"secret" value:"cert" > label:<name:"serial_number" value:"12345678901234567890" > label:<name:"subject_C" value:"EU" > label:<name:"subject_CN" value:"M1" > label:<name:"subject_O" value:"OK" > gauge:<value:0 > } was collected before with the same name and label values
```

Logs of the x509-certificate-exporter pod looks ok:

```
time="2021-09-11T18:43:07Z" level=info msg="fetching configuration from within the cluster"
time="2021-09-11T18:43:07Z" level=info msg="loaded configuration, API server is at https://112.65.0.1:443"
time="2021-09-11T18:43:07Z" level=info msg="fetching API server version"
time="2021-09-11T18:43:07Z" level=info msg="kubernetes server version is v1.19.7"
time="2021-09-11T18:43:07Z" level=info msg="starting x509-certificate-exporter version 2-10-0"
time="2021-09-11T18:43:08Z" level=info msg="5 valid certificate(s) found in \"k8s/app/default-cert\""
time="2021-09-11T18:43:08Z" level=info msg="parsed 5 certificates (0 read failures)"
time="2021-09-11T18:43:08Z" level=info msg="listening on :9793"
```

What can cause this problem and how I can fix it? Maybe it is a bug or my mistake? Thank you for your help!

**Comment by arcln** [comment]
Hello! I need more informations to be sure, but I think it's a problem on your end. I can see in the logs that the exporter found a k8s secret named `default-cert` in namespace `app`. This secret seems to contains 5 different PEM blocks each containing an x509 certificate. I suspect that two of these blocks contains the same certificate, which is causing this error.

Please double check if all the 5 certificates are different (at least one unique field in the distinguish names). If you still can't figure out the problem, please provide us with as many as possible informations about these 5 certs (having the certs themselves would be ideal). Also if you _need_ to handle duplicate certs, please provide us with an example use case so we can think about it.

**Comment by testisnullus** [comment]
Hi! Thanks a lot for you answer! I've already fixed this issue. The problem was that I actually had two identical certificates in one k8s secret. I think we can close this issue without a doubt.

I really appreciate the work that you've done working on this perfect exporter. It is easy to install, flexibly configurable and works great!

With best regards,
Danil
