### ISSUE TITLE
Push image to quay.io

### ISSUE THREAD

**Issue by DebakelOrakel** [enix/x509-certificate-exporter#22]
It would be nice to also push the image to another container registry like quay.io.
Docker.io has pull limits, which can cause problems.

**Comment by npdgm** [comment]
Hi, thanks for opening the issue, that's a good suggestion :+1: 
We now have [a repository at quay.io](https://quay.io/repository/enix/x509-certificate-exporter?tab=tags) readily available with all v2 tags.
Keeping this open for now as the CI has to be tweaked to push on both registries.
Cheers

**Comment by DebakelOrakel** [comment]
Great! ...and fast 😄 

Thank you very much.

**Comment by npdgm** [comment]
You're welcome :rocket: 
CI was changed so that future releases are pushed to both registries.
Cheers
