### ISSUE TITLE
Check a pem encoded tls certificate inside a pod

### ISSUE THREAD

**Issue by jsammut1976** [enix/x509-certificate-exporter#260]
### Discussed in https://github.com/enix/x509-certificate-exporter/discussions/245

<div type='discussions-op-text'>

<sup>Originally posted by **jsammut1976** February  7, 2024</sup>
I am aware that this x509 exporter may be used to watch hostpath directories in a k8s cluster.

Can this exporter be used to monitor a pem encoded certificate which resides in a pod's filesystem instead? (not in a directory in the hosting k8s node)?
</div>

**Comment by paullaffitte** [comment]
Hello,

This would require to run the exporter as a side-car of your pod and while this is technically possible, it is not a feature that we plan to officially support for now as part of the helm chart. In this regard I'm closing the issue, but feel free to ask questions if you need help about how to configure it as a side-car.
