### ISSUE TITLE
golang.org/x/text package vulnerable 

### ISSUE THREAD

**Issue by vutkin** [enix/x509-certificate-exporter#31]
I've scan image using trivy and found an issue with vulnerability of golang.org/x/text

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/25753488/175555083-06aa32bc-010a-4a8a-8a2f-a34dccb12a93.png">

Could you please bump version to 0.3.7?

**Comment by vutkin** [comment]
PR: https://github.com/enix/x509-certificate-exporter/pull/32/files

**Comment by vutkin** [comment]
@arcln , could you please create a release with this fix?

**Comment by vutkin** [comment]
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/25753488/175919673-26578ad9-a562-4886-8826-e102e6279343.png">
Looks good now. Thanks! When do you plan to release `3.0.1` version by the way?

**Comment by arcln** [comment]
Hello, I will release 3.0.1 by tomorrow I just need to fix another issue and do some internal testing.
