### ISSUE TITLE
Release schedule for v3.15.0

### ISSUE THREAD

**Issue by tuminoid** [enix/x509-certificate-exporter#322]
Hello maintaines!

It has been a while since previous release, 4 months or so, and meanwhile a lot of vulnerabilities has been patched in Go and your deps. Go 1.22.5 build is needed to plug those. Those bumps have landed in the project already (yay!), but an offiical release/chart/image containing said fixes are missing. Is there any timeline, roadmap or schedule for the release and what are the missing items for it to be done? 

Refs:
- https://osv.dev/vulnerability/GO-2024-2824
- https://osv.dev/vulnerability/GO-2024-2887
- https://osv.dev/vulnerability/GO-2024-2963

**Comment by npdgm** [comment]
Hi @tuminoid 
Thanks for raising the issue, we are indeed overdue for a release.
Working on it now
Cheers

**Comment by npdgm** [comment]
Release is in progress: https://github.com/enix/x509-certificate-exporter/actions/runs/10596321140

**Comment by tuminoid** [comment]
Thanks @npdgm, much appreciated!

**Comment by npdgm** [comment]
Version 3.15.0 is available on container registries and the Helm repository.
Thanks again
