### ISSUE TITLE
Helm chart: add alertExtraLabels and rulePrefix to prometheusrule; adjust README.md

### ISSUE THREAD

**Issue by vutkin** [enix/x509-certificate-exporter#36]
Helm chart changes:
- add alertExtraLabels and rulePrefix to prometheusrule;
- adjust README.md.

**Comment by npdgm** [comment]
Hi @vutkin
Thanks a lot for your contribution in #35 :rocket: 
I ran helm-docs again with alphanumeric ordering disabled, and left a note about this.
Cheers

**Comment by vutkin** [comment]
It will be great to release new version of helm chart. @npdgm Do you have any plans?

**Comment by npdgm** [comment]
@vutkin it has been released as version 3.1.0 now. Sorry it went though the beta channel before.
