### ISSUE TITLE
Is there a way to decode pfx file with the x509-certificate-exporter?

### ISSUE THREAD

**Issue by strossan** [enix/x509-certificate-exporter#42]

**Comment by npdgm** [comment]
Hi,
Implementing support for PKCS#12 has been evaluated a couple times. When working on version 3 we investigated what libraries could be used, as the standard golang library barely provide interfaces for this format.
We ultimately decided not to support PKCS#12.

Friction points are:
- unsatisfactory standard library and wish not to depend on large crypto packages
- conflicts on how to handle both formats: probing files doesn't feel like a clean method, and the remaining choice is to significantly refactor code and command-line arguments
- PKCS#12 bundles are more complex and raise problems we didn't have to handle with PEM blobs. We don't want to purposely ignore corner cases.
- likely risk of having to alter metrics specifications

So eventually we will only support PEM for the time being. Design choices have been made on these premises and it keeps things simple and easier to maintain.
