### ISSUE TITLE
OpenBSD release builds

### ISSUE THREAD

**Issue by tacerus** [enix/x509-certificate-exporter#44]
Hello!

Any chance we could get builds for OpenBSD published as part of future releases?

Best,
Georg

**Comment by tacerus** [comment]
Now that was a fast! :-)

Thank you so much for this - I assume they will work fine, given the manually compiled version did, but I will try it out tomorrow and report back!

**Comment by npdgm** [comment]
You're welcome!
I was troubleshooting the Gitlab CI, as we had problems releasing on this project last week. It was convenient triggering a new release.

**Comment by tacerus** [comment]
Great! Can confirm it works flawlessly on OpenBSD 7.1 amd64.

Shall I submit a PR for an rc service file, possibly in a `contrib/openbsd/` directory, or do you deem it out of scope of the project?

**Comment by tacerus** [comment]
Ah, that makes sense. :-)

Sweet! I sent it via #46 and will close this issue since the new binary is working great!
