### ISSUE TITLE
Provide steps for deploying x509-exporter on kubernetes

### ISSUE THREAD

**Issue by milindchawre** [enix/x509-certificate-exporter#5]
The contents of the current README.md file is not sufficient for deploying this exporter on k8s.

It [seems](https://stackoverflow.com/questions/63208043/is-there-a-way-to-monitor-tls-certificates-in-kubernetes-using-prometheus) there are people out there trying to deploy it on k8s, but find it difficult.

**Comment by rdegez** [comment]
Indeed the README.md is a bit light, we will definitely improve this!

In the meantime, you can find some useful informations in the helm chart we made for it :
[https://github.com/enix/helm-charts/tree/master/charts/x509-exporter](https://github.com/enix/helm-charts/tree/master/charts/x509-exporter)

**Comment by arcln** [comment]
Hi, we now provide a fully-featured and documented [Helm chart](https://github.com/enix/helm-charts/tree/master/charts/x509-certificate-exporter) for deploying this exporter on k8s.
