### ISSUE TITLE
Can't see nothing on grafana with kube-prometheus-stack

### ISSUE THREAD

**Issue by mamu-reply** [enix/x509-certificate-exporter#78]
Hi Guys!
I've installed Prometheus and Grafana with the kube-prometheus-stack helm, and then i've installed the x509-certificate-exporter helm.
I've tried different configurations but no one work, i can't see new metrics on prometheus and i can't see the kubernetes\Certificates (x509-exporter) folder on grafana.
My tests:
- Normal installation with Helm without change the values.yaml in the same namespace of kube-prometheus-stack
- Normal installation with Helm without change the values.yaml in a different namespace
- This values config: (all values in different combinations)
```
         "prometheusServiceMonitor":
            "create": true
            "extraLabels":
              "release": "kube-prometheus-stack"
          "prometheusPodMonitor":
            "create": true
            "extraLabels":
              "release": "kube-prometheus-stack"
          "prometheusRules":
            "extraLabels":
              "release": "kube-prometheus-stack"
          "secretsExporter":
            "podExtraLabels":
              "release": "kube-prometheus-stack"
          "service":
            "extraLabels":
              "release": "kube-prometheus-stack"
          "hostPathsExporter":
            "podExtraLabels":
              "release": "kube-prometheus-stack"
```

I'm using the x509 latest version 3.6.0, and the 41.6.1 kube-prometheus-stack version.

I don't know if i have to add other values or if i've to change something into the kube-prometheus-stack values.yaml.
If i see the x509 pod it is un and running and log say that everything is fine, and if i see the prometheus-operator logs there are nothing about the x509-certificate-exporter.

I don't know what else to do, please help me.

**Comment by npdgm** [comment]
Hi @mamu-reply 

> i can't see the kubernetes\Certificates (x509-exporter) folder on grafana

It's expected as we do not ship the Grafana dashboard with the Chart. You'll have to add the dashboard from the Grafana frontend using ID `13922`, or if you're air gaped then [grab the JSON at the download page](https://grafana.com/grafana/dashboards/13922-certificates-expiration-x509-certificate-exporter/).
When lacking persistence on the Grafana deployment, an other option is to put the JSON in an extra ConfigMap through kube-prometheus-stack values.

You raised a good point, we may be able to have the Grafana sidecar pick a dashboard deployed with our chart. There used to be issues with namespaces but that may be ok now.
I'll look into that!

> i can't see new metrics on prometheus
> the prometheus-operator logs there are nothing about the x509-certificate-exporter

I trust you didn't miss any log but it should be there though, whether the operator accepted or ignored a "Monitor" object.
Did you watch the log *while* uninstalling then installing the chart for the exporter?
You were right to try installing in the same namespace of kube-prometheus-stack, this configuration should work out of the box on any cluster.

Let me try installing the same versions you have tomorrow, and I'll let you know.
What's your Kubernetes version? and distribution? (kubeadm, RKE, OpenShift, cloud provider, ...)

In the meantime I'd be interested to have a look at your Prometheus resource, especially all attributes with names ending with 'MonitorSelector' if you don't feel like copying it all.
```
$ kubectl get -A Prometheus -o yaml | grep 'MonitorSelector:'
```

Cheers

**Comment by mamu-reply** [comment]
> 

**THANKS**! 
With the ID the import work! Yes can be really cool if the sidecar will be deployed automatically 😄 
Honestly i don't know why i don't se any log in the prometheus-operator pod about the x509, but with this configuration now work and i can see metrics:
**x509-certificate-operator**
```
          "prometheusServiceMonitor":
            "create": true
            "extraLabels":
              "release": "kube-prometheus-stack"
          "prometheusPodMonitor":
            "create": true
            "extraLabels":
              "release": "kube-prometheus-stack"
          "prometheusRules":
            "extraLabels":
              "release": "kube-prometheus-stack"
          "secretsExporter":
            "podExtraLabels":
              "release": "kube-prometheus-stack"
          "service":
            "extraLabels":
              "release": "kube-prometheus-stack"
          "hostPathsExporter":
            "podExtraLabels":
              "release": "kube-prometheus-stack"
```

**kube-prometheus-stack**
```
          "prometheus":
            "prometheusSpec":
              "enableRemoteWriteReceiver": true
              "remoteWriteDashboards": true
              "ruleSelectorNilUsesHelmValues": true
              "serviceMonitorSelectorNilUsesHelmValues": true
              "podMonitorSelectorNilUsesHelmValues": true
              "probeSelectorNilUsesHelmValues": true
            "thanosService":
              "enabled": true
            "thanosServiceMonitor":
              "enabled": true
```
both in the same namespace.
If you want also try i'm using:
- kubectl version : 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:33:06Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.15-eks-fb459a0", GitCommit:"be82fa628e60d024275efaa239bfe53a9119c2d9", GitTreeState:"clean", BuildDate:"2022-10-24T20:33:23Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```
- AWS EKS with kubernetes 1.22
- Everything is installed with ArgoCD app of apps

**Comment by npdgm** [comment]
Sorry I did not find the means and opportunity to try replicate your issue.
Glad you got it running fine :+1:
