### ISSUE TITLE
Do not treat "non-PEM" files as exporter errors

### ISSUE THREAD

**Issue by tgdfool2** [enix/x509-certificate-exporter#98]
Hi All,

First of all, thanks a lot for this great project that drastically help monitoring certificate expiration on self-managed Kubernetes clusters!

We are using it in `DaemonSet` mode with the `watchDirectories` setting to specify which directories should be monitored. This is very handy, as new certificates that will be stored in these directories will automatically be monitored. BUT... These directories also contain other files (like `.key`, `.csr`, `.conf`, etc.), which are not meant to be monitored by this tool. Unfortunately, these files are reported as "exporter errors" and are "polluting" our alerting system.

Question: Is there a way to prevent the "non-PEM" files to be treated as exporter errors?

Thanks in advance for your help!

```
❯ k logs -f x509-certificate-exporter-controlplane-6jcpw
time="2023-01-09T09:26:16Z" level=info msg="starting x509-certificate-exporter version 3.6.0 (0dd5e2318ae07e33778a72f53cd6e6ac8dbe0931) (2022-10-27T14:48:07)"
time="2023-01-09T09:26:16Z" level=info msg="1 valid certificate(s) found in \"/mnt/watch/dir-891a355f5967c209def0469b890e5f2f129fc1de/etc/kubernetes/pki/etcd/peer.crt\""
time="2023-01-09T09:26:16Z" level=warning msg="no certificate(s) found in \"/mnt/watch/dir-891a355f5967c209def0469b890e5f2f129fc1de/etc/kubernetes/pki/etcd/peer.key\""
time="2023-01-09T09:26:16Z" level=info msg="1 valid certificate(s) found in \"/mnt/watch/dir-891a355f5967c209def0469b890e5f2f129fc1de/etc/kubernetes/pki/etcd/server.crt\""
time="2023-01-09T09:26:16Z" level=warning msg="no certificate(s) found in \"/mnt/watch/dir-891a355f5967c209def0469b890e5f2f129fc1de/etc/kubernetes/pki/etcd/server.key\""
```

**Comment by tgdfool2** [comment]
FYI, this can be worked around by using `watchFiles` and file globbing instead of `watchDirectories` (see https://github.com/enix/x509-certificate-exporter/issues/48#issuecomment-1646656190 for more information)

**Comment by jslouisyou** [comment]
Hello @tgdfool2 , Could you please let me know some examples how did you get this?

**Comment by tgdfool2** [comment]
Hi @jslouisyou. Sorry, I'm not working on the project using `x509-certificate-exporter` anymore.
